# -*- coding: utf-8 -*-
"""2026-09-23 盘后档：新闻增量构建（窗口 14:00-20:00，含当日全量收盘信息）
⚠️ §3.96：源头一律用中文引号、一字段一行、写盘后 ast.parse() 预检
"""
import json, os, ast
from collections import Counter

BASE = "/Users/jieyang/Documents/WealthHub"
OUT = os.path.join(BASE, "data/processed/news/news-close-20260923.json")

SRC = r'''
[
 {"track": "宏观", "category": "行业事件类",
  "title": "A股9月23日缩量收跌：上证指数收报3936.52点（-0.39%）、深证成指13636.07（-0.64%）、创业板指3379.61（-0.60%）、沪深300 4517.28（-0.60%）、科创50 1660.85（-0.25%），北证50逆势大涨2.60%报1074.04；沪深两市成交1.76万亿元，较前一交易日缩量约3706亿元；1891只个股上涨、3564只下跌，51只涨停、14只跌停",
  "summary": "量能大幅萎缩而下跌家数扩大至3564只、跌停增至14只，属「买盘退潮型地量」而非「抛压枯竭型地量」；节前避险特征确认，指数级方向不具参与价值。",
  "source": "腾讯新闻/新浪财经/网易财经", "source_url": "https://news.qq.com/rain/a/20260923A08HFM00",
  "sentiment": "负面", "score": 68, "strength": 68, "direction": "利空", "volatility": "中", "brief": "缩量3706亿、3564股下跌、14股跌停"},
 {"track": "宏观", "category": "宏观类",
  "title": "习近平于9月23日至25日对美国进行国事访问、周四举行元首会晤：议程包括延长去年达成的中美贸易休战、人工智能监管、美国对台军售；美方称9月20日纽约经贸磋商为「总体平衡积极的成果」；但华尔街普遍预期突破有限，且中方未带大型CEO代表团",
  "summary": "本周最大定价变量。若释放缓和信号，出口链、科技链与港股同步受益；若生物技术/药品议题被纳入限制清单或会谈不及预期，则节前波动放大。",
  "source": "Yahoo Finance/Reuters/tl;dr daily news", "source_url": "https://finance.yahoo.com/markets/stocks/articles/wall-st-futures-muted-mideast-114116425.html",
  "sentiment": "中性", "score": 62, "strength": 62, "direction": "中性", "volatility": "高", "brief": "元首会晤周四举行，预期突破有限"},
 {"track": "恒生科技", "category": "行业事件类",
  "title": "海外大模型降价潮引发AI资产重估：港股智谱跌12.40%、天数智芯跌8.75%、海清智元跌6.29%，大型科网股同步承压（阿里巴巴跌超4%、小米集团跌超3%、腾讯控股跌2.35%收441港元、百度跌超1%）；A股AI应用与传媒营销方向同步回撤（软件指数ETF跌1.72%居跌幅榜首、云计算ETF跌1.67%）",
  "summary": "市场担忧从「变现能力」转向「毛利率与现金流确定性」——降价潮下连腾讯、阿里亦难独善其身，两地科技资产在该逻辑上连通，是本档组合恒科赛道与传媒持仓的共同拖累源。",
  "source": "腾讯新闻/网易财经/新华社", "source_url": "https://www.163.com/dy/article/L7HGVFT005346RC6.html",
  "sentiment": "负面", "score": 74, "strength": 74, "direction": "利空", "volatility": "高", "brief": "大模型降价潮，智谱跌12%阿里跌超4%"},
 {"track": "宏观", "category": "宏观类",
  "title": "利率与商品：CME 定价10月再加息25bp概率回落至约50%（前一日54.2%），美债收益率小幅回落、美元指数维持100.5上方强势；布伦特原油回落至约99美元/桶（近两周首次跌破100）、WTI跌破90美元，为五连跌，沙特重启东西向输油管道恢复延布出口；铜价创历史新高、黄金区间震荡",
  "summary": "油价持续下行同时缓解输入性通胀与压制油气链，加息概率边际回落对成长股估值分母偏正面，但美元强势仍构成压制，方向未定。",
  "source": "Saxo Bank/Yahoo Finance", "source_url": "https://www.home.saxo/content/articles/macro/market-quick-take---oil-slips-under-90-as-bank-shares-slide---23-september-2026-23092026",
  "sentiment": "正面", "score": 58, "strength": 58, "direction": "利多", "volatility": "中", "brief": "加息概率回落至50%，油价五连跌"},
 {"track": "宏观", "category": "行业事件类",
  "title": "A股资金结构：主力资金净流入电子板块超157亿元，居31个申万一级行业首位（科创芯片ETF一度涨近1%、收跌0.26%）；催化为阿里云栖大会千问参数向5-10T扩展、Meta智能体Muse提振CPU需求预期、美银上调存储涨价预期；医药生物亦获资金净流入",
  "summary": "存量博弈下资金高度集中于电子（AI硬件/存储/覆铜板）与医药两条有产业验证的主线；传媒、煤炭、油气则成为资金来源，结构分化极端。",
  "source": "新浪财经/同壁财经", "source_url": "https://cj.sina.com.cn/articles/view/7651844612/1c815e204001020j1m?finpagefr=p_103",
  "sentiment": "正面", "score": 56, "strength": 56, "direction": "利多", "volatility": "中", "brief": "电子净流入157亿居申万首位"},
 {"track": "A股医药", "category": "行业事件类",
  "title": "医药成为9月23日全市场唯一亮点：疫苗生物ETF（561920）涨1.60%居涨幅榜首位、生物科技ETF（159849）涨0.35%、医疗器械ETF（159898）涨0.20%；个股端奥浦迈涨超16%、益诺思涨超14%、义翘神州涨超11%、百普赛斯涨超10%、昊帆生物涨超9%，艾力斯/皓元医药/禾元生物-U/美迪西涨超8%，欧林生物涨超7%，康希诺/南华生物涨超6%",
  "summary": "在全市场超3500只个股下跌的弱势格局中，医药是唯一形成板块效应的方向；但强势集中在小市值CRO/科研试剂，组合暴露的大市值与主动基受益被结构性打折。",
  "source": "腾讯新闻/网易财经", "source_url": "https://www.163.com/dy/article/L7HEJKRB0519QIKK.html",
  "sentiment": "正面", "score": 85, "strength": 85, "direction": "利多", "volatility": "高", "brief": "医药逆势成唯一亮点，CRO涨超10%"},
 {"track": "A股医药", "category": "政策类",
  "title": "医药工业「十五五」规划持续发酵，花旗发布研报：规划核心是推动中国医药工业由规模驱动转向创新驱动与质量导向，明确2030年跻身世界领先行列，覆盖创新药、创新医疗器械、AI驱动药物发现及CDMO/CRO，政策对整条价值链作出广泛支持；花旗认为利好创新药/生物科技、AIDD公司、CRO/CDMO、高端医疗器械及IVD、创新中药",
  "summary": "外资卖方首次以「整条价值链」口径背书政策，把医药从主题炒作抬升为「有政策+订单双重验证的独立景气成长板块」，对组合 A股医药 23.58% 暴露构成中期支撑。",
  "source": "腾讯新闻/花旗研报", "source_url": "https://news.qq.com/rain/a/20260923A05LZ300",
  "sentiment": "正面", "score": 80, "strength": 80, "direction": "利多", "volatility": "中", "brief": "花旗：政策支持医药全价值链"},
 {"track": "A股医药", "category": "行业事件类",
  "title": "产业催化三线共振：①莫德纳与默沙东联合开发的个体化mRNA新抗原疗法三项研究摘要获2026年ESMO大会接收，提振mRNA疫苗链；②诺和诺德与Anthropic合作将Claude模型接入药物研发，AI制药赛道全球巨头9月以来密集落子；③黑龙江省推出23价肺炎球菌多糖疫苗接种惠民行动，疫苗概念获地方政策叠加",
  "summary": "mRNA与AI制药提供短期产业验证，地方疫苗惠民行动提供支付端增量，三条线索共同支撑医药独立景气叙事。",
  "source": "腾讯新闻/网易财经", "source_url": "https://news.qq.com/rain/a/20260923A0A7G600",
  "sentiment": "正面", "score": 72, "strength": 72, "direction": "利多", "volatility": "中", "brief": "mRNA+AI制药+地方疫苗惠民三线共振"},
 {"track": "A股医药", "category": "业绩类",
  "title": "医药研发端新增进展：长春高新子公司百克生物收到NMPA下发的重组人源抗RSV单克隆抗体注射液组合制剂临床试验申请《受理通知书》；天演药业双masked HER2×CD3双特异性T细胞衔接器ADG138获NMPA IND批准，计划2026年Q4启动I期临床；另人民日报报道今年以来中国创新药对外授权交易总额突破1200亿美元、同比增长36%",
  "summary": "国内研发管线持续推进叠加出海授权高增，验证「创新药收入+44.1%、CXO+23.3%」的中报景气延续性。",
  "source": "新浪财经/新浪财经公告/人民网", "source_url": "https://finance.sina.com.cn/",
  "sentiment": "正面", "score": 64, "strength": 64, "direction": "利多", "volatility": "中", "brief": "RSV单抗受理+创新药出海破1200亿美元"},
 {"track": "A股医药", "category": "行业事件类",
  "title": "FDA 监管风险个案延续：圣诺生物(688117.SH)全资子公司成都圣诺生物制药在2026年8月FDA现场检查后被列入第66-40号进口警示名单，警示解除前相关多肽原料药产品全面暂停对美销售与发运；公司上半年美国市场收入占比超三成，多肽CDMO业务受影响重大",
  "summary": "与9/29进口专利药关税扩围形成叠加，说明「对美依赖度高的原料药/CDMO环节」是当前医药板块最明确的个股级监管风险点。",
  "source": "圣诺生物公告/科创板日报", "source_url": "https://www.163.com/dy/article/L7GJDC4705199NHJ.html",
  "sentiment": "负面", "score": 65, "strength": 65, "direction": "利空", "volatility": "中", "brief": "圣诺生物多肽原料药全面停发对美"},
 {"track": "A股医药", "category": "行业事件类",
  "title": "小票炒作降温信号延续：南华生物（此前4连板）公告澄清「细胞治疗相关技术与产品尚处于研发阶段，无创新药上市或进入到临床试验阶段」；本档板块内强势股仍以CRO/科研试剂小票为主（奥浦迈、益诺思、义翘神州、百普赛斯），龙头端未同步跟涨",
  "summary": "政策主线的第三、第四个观察日仍为「小票驱动、龙头不接」，与9/21结构确认日形成反差，主动基弹性档位须继续按全样本中位档并给出区间。",
  "source": "腾讯新闻/新浪财经", "source_url": "https://news.qq.com/rain/a/20260923A08HFM00",
  "sentiment": "负面", "score": 55, "strength": 55, "direction": "利空", "volatility": "高", "brief": "南华生物澄清无创新药，小票降温"},
 {"track": "大消费", "category": "政策类",
  "title": "文化和旅游部9月23日正式启动2026年全国国庆文化和旅游消费月，活动自9月下旬持续至10月底，各地举办超2万场次文旅活动、发放超3.1亿元消费券等消费补贴；全国多地密集跟进——洛阳推出近50场促消费活动、北京通州发放200万元消费券并联动近200家商户、成都高新区推出128场文商旅活动、云南省商务厅携手京东秒送派发「彩云金秋」双节消费券；重庆市整合让利超7亿元并推出超500场促消费活动",
  "summary": "双节是激活内需的关键窗口，中央+地方消费券与活动密度为历史高位，构成大消费板块的短期事件性支撑；但补助方式仍以「以旧换新+消费券」为主，对白酒等高端可选消费品类传导有限。",
  "source": "腾讯新闻/重庆日报/新华网重庆频道", "source_url": "https://news.qq.com/rain/a/20260923A056L600",
  "sentiment": "正面", "score": 68, "strength": 68, "direction": "利多", "volatility": "中", "brief": "文旅消费月启动，发放超3.1亿元消费券"},
 {"track": "大消费", "category": "业绩类",
  "title": "中信证券发布研报判断白酒行业底部已至：头部酒企加速出清、库存去化、量价触底、供给主动收缩、渠道生态改善、市场预期低位等底部特征已逐步显现；今年以来宏观层面积极信号从多个维度逐步积累，行业整体动销同比降幅已有一定程度收窄，若未来需求逐步企稳，考虑2025年基数效应，预计2026年第二季度开始白酒公司业绩表现有望出现一定程度改善",
  "summary": "头部券商首次给出明确的时间锚（2026Q2）与底部定性，与国海/华创的底部区间判断形成卖方共识；但「动销降幅收窄」不等于需求转正，纪律上仍不足以支撑加仓。",
  "source": "中信证券（北京商报/腾讯新闻转载）", "source_url": "https://news.qq.com/rain/a/20260923A0964A00",
  "sentiment": "正面", "score": 72, "strength": 72, "direction": "利多", "volatility": "中", "brief": "中信证券：白酒底部已至，2026Q2改善"},
 {"track": "大消费", "category": "行业事件类",
  "title": "白酒板块9月23日收跌：白酒板块指数以1902.83点收盘下跌0.61%，11只白酒股下跌；贵州茅台收1251.24元（-0.20%）、五粮液70.34元（-0.28%）、山西汾酒114.03元（+0.73%）、泸州老窖72.11元（+0.88%）、洋河股份38.03元（-0.83%）；中证白酒指数收6237.18（-0.23%）、中证消费收12288.79（-0.27%）",
  "summary": "研报催化未能转化为资金行为：「底部已至」的定性未获价格确认，白酒全天窄幅收跌，验证「供给端率先出清、需求端待验证」的定性维持。",
  "source": "北京商报/腾讯新闻/同花顺", "source_url": "https://news.qq.com/rain/a/20260923A0964A00",
  "sentiment": "负面", "score": 55, "strength": 55, "direction": "利空", "volatility": "低", "brief": "白酒板块收跌0.61%，11只个股下跌"},
 {"track": "大消费", "category": "行业事件类",
  "title": "大消费内部结构：黄酒概念继续活跃（古越龙山涨5.00%、天佑德酒涨3.97%、来伊份涨2.18%），会稽山盘中走出7天5板、股价创历史新高、一个月累计涨幅超100%；华泰证券研报判断黄酒行业量价逻辑有望迎来重构（量的弹性来自江浙沪渗透率提升与全国拓展，价的维度来自竞争格局优化下的高端化）；白酒概念板块整体收跌0.57%",
  "summary": "资金在消费内部寻找「新叙事」（黄酒、区域酒）而非回流高端白酒，说明市场对白酒需求端的信心仍未恢复，结构性行情特征明显。",
  "source": "同花顺/腾讯新闻", "source_url": "https://field.10jqka.com.cn/20260923/c680222466.shtml",
  "sentiment": "中性", "score": 52, "strength": 52, "direction": "中性", "volatility": "高", "brief": "黄酒概念活跃，会稽山7天5板创新高"},
 {"track": "恒生科技", "category": "行业事件类",
  "title": "港股9月23日三大指数集体下挫：恒生指数跌253.63点、跌幅1.01%收报24834.12点（全日主板成交1843.07亿港元，较前一日2492.14亿港元明显萎缩）；恒生科技指数跌59.14点、跌幅1.33%收报4379.07点；恒生国企指数跌88.79点、跌幅1.06%收报8273.81点；南向资金延续净流入",
  "summary": "指数下跌而量能收缩，抛压主要来自权重股的结构性调整而非全面恐慌；恒生科技自9/22盘中高点4510.06累计回落2.91%，「催化当日即兑现」的剧本进入确认阶段。",
  "source": "新华社/网易财经", "source_url": "https://www.163.com/dy/article/L7HGVFT005346RC6.html",
  "sentiment": "负面", "score": 72, "strength": 72, "direction": "利空", "volatility": "中", "brief": "恒指-1.01%、恒科-1.33%，成交萎缩"},
 {"track": "恒生科技", "category": "行业事件类",
  "title": "港股逆势方向：内房股大涨（融信中国涨22.22%、富力地产涨4.88%、万科企业涨4%、碧桂园涨超2%），物业股走强（世茂服务涨11.76%、万物云涨1.72%、华润万象生活涨1.71%），PCB概念两地共振（建滔积层板涨超11%、建滔集团涨超5%、胜宏科技涨超3%）；催化为9月19日上海二手房（含商业）单日网签成交1495套创2026下半年单日纪录、新修订《住房公积金管理条例》9月20日落地实施",
  "summary": "资金在港股内部由AI应用切向地产链与算力硬件配套；地产政策与基本面回暖构成恒科之外的独立线索，但组合无相关暴露。",
  "source": "腾讯新闻/网易财经", "source_url": "https://news.qq.com/rain/a/20260923A06JIK00",
  "sentiment": "正面", "score": 55, "strength": 55, "direction": "利多", "volatility": "中", "brief": "内房股大涨，融信中国+22.22%"},
 {"track": "恒生科技", "category": "行业事件类",
  "title": "港股科技龙头回购延续与估值回落：腾讯控股9月23日斥资1亿港元回购22.3万股、百度回购4999.58万港元、小米回购4892.85万港元；恒生科技指数PE(TTM)回落至23.23、估值分位34.83%，较前一日的39.53%单日回落4.70个百分点，为26只核心指数中分位回落最快",
  "summary": "估值单日被动下修 4.70 个百分点后，恒科已回到近十年约三分之一分位，中期性价比改善；但机构普遍认为本轮反弹源于空头回补而非基本面改善，短期仍需等订单验证。",
  "source": "腾讯新闻/理杏仁", "source_url": "https://news.qq.com/rain/a/20260923A06JIK00",
  "sentiment": "正面", "score": 55, "strength": 55, "direction": "利多", "volatility": "中", "brief": "恒科PE分位单日回落4.7pct至34.83%"},
 {"track": "美股标普医药", "category": "政策类",
  "title": "【重磅】美国商务部工业与安全局(BIS)于9月23日发布公告(Docket 260918-0006)，落实第11020号总统公告第3(d)条：孤儿药、核药、血浆衍生疗法、生育用药、细胞治疗产品、基因治疗产品、抗体药物偶联物(ADC)、CBRN医学对策、动物保健产品共9类特殊药品，凡原产于欧盟、日本、英国、韩国、瑞士与列支敦士登、印度、印尼、泰国、越南等20个列名辖区，或符合「美国紧迫健康需求」者，可适用零关税；同时新增HTSUS 9903.04.70 项下对「仅用于临床试验、研发或其他非商业用途」的药品及成分零关税；均自2026年9月29日美东00:01起生效",
  "summary": "对9/29进口专利药100%关税扩围的重大对冲：政策从「一刀切」转为「分类豁免+分层管理」，孤儿药/基因治疗/ADC等高价值创新药获得明确零关税通道，直接缓解组合美股标普医药15.55%暴露的尾部风险。",
  "source": "美国联邦公报/BIS/PolicyRisk", "source_url": "https://policyrisk.com/federal-register/2026-19498",
  "sentiment": "正面", "score": 82, "strength": 82, "direction": "利多", "volatility": "中", "brief": "BIS发布零关税指引，9类药品豁免"},
 {"track": "美股标普医药", "category": "政策类",
  "title": "同一公告的技术性内容：明确「通用药品(generic pharmaceutical articles)」定义包含「未专利动物保健产品」；规定企业可通过 pharma232@bis.doc.gov 持续提交单品「美国紧迫健康需求」申请，商务部会同USTR与HHS逐案书面裁定后由CBP在报关时适用；并对附件一/附件四作5+1处技术更正；因需在9月29日生效前完成受理，BIS援引紧急情况绕过常规《文书工作削减法》审查程序",
  "summary": "程序细节确认「豁免是常态化通道而非一次性让步」，且RD/临床用途零关税进一步降低研发端成本；对创新药占比高的美股医药指数属中期结构性利好。",
  "source": "The Political Risk Brief/联邦公报", "source_url": "https://tetmo.com/political-risk-brief/the-political-risk-brief-wednesday-september-23-2026",
  "sentiment": "正面", "score": 58, "strength": 58, "direction": "利多", "volatility": "低", "brief": "零关税为常态化通道，RD用途亦豁免"},
 {"track": "其他/宽基", "category": "行业事件类",
  "title": "传媒影视成为9月23日最弱方向：中信出版跌超12%，华媒控股、龙版传媒、中视传媒跌停，欢瑞世纪、奥飞娱乐、上海电影跌幅居前；对应组合传媒ETF（512980）收0.813元、跌2.75%，为组合内最大单品种跌幅",
  "summary": "传媒的下跌是「AI应用叙事退潮」的直接映射（昨日领涨、今日跌停），说明在缩量环境下热点的次日存活率极低，组合传媒持仓属被卷入的结构性风险而非个股事件。",
  "source": "腾讯新闻/每日经济新闻", "source_url": "https://news.qq.com/rain/a/20260923A08HFM00",
  "sentiment": "负面", "score": 70, "strength": 70, "direction": "利空", "volatility": "高", "brief": "传媒影视跌停潮，传媒ETF-2.75%"},
 {"track": "其他/宽基", "category": "行业事件类",
  "title": "A股领跌与领涨结构：领跌为煤炭开采加工（中证煤炭跌2.16%，26只核心指数中跌幅最大；云煤能源跌停、郑州煤电跌超8%）、文化传媒与影视院线、油气开采及服务、游戏、电力；领涨为AI硬件与地产两条线——覆铜板涨3.13%、量子计算涨2.92%、电子树脂涨2.63%、靶材涨2.61%、复合集流体涨2.58%、房地产服务涨3.31%、肿瘤疫苗涨2.41%",
  "summary": "在3564只个股下跌的背景下，资金只向「有明确产业或政策事件驱动」的方向集中；组合内的红利ETF（-0.77%）、证券ETF（-0.37%）等宽基与防御资产普遍回落，构成其他/宽基赛道的拖累来源。",
  "source": "新浪财经/腾讯新闻", "source_url": "https://finance.sina.com.cn/stock/s/2026-09-23/doc-inisvivx8542081.shtml",
  "sentiment": "负面", "score": 58, "strength": 58, "direction": "利空", "volatility": "中", "brief": "煤炭传媒领跌，AI硬件与地产领涨"},
 {"track": "其他/宽基", "category": "行业事件类",
  "title": "组合相关个股与场内标的全天收盘：广联达8.46元（-1.86%）、通威股份11.58元（-1.19%）、贵州茅台1251.24元（-0.20%）；9只场内ETF中中概互联网ETF易方达(513050) 1.030（-1.90%）、传媒ETF广发(512980) 0.813（-2.75%）为最大拖累，消费ETF(159928) 0.656（-0.30%）、医药ETF(159938) 0.654（+0.15%）、医疗ETF华宝(512170) 0.349（+0.29%）、恒生科技ETF华夏(513180) 0.552（-1.08%）、恒生ETF(159920) 1.460（-0.88%）、证券ETF国泰(512880) 1.065（-0.37%）、红利ETF易方达(515180) 1.412（-0.77%）",
  "summary": "个股端广联达单日-1.86%贡献约-717元，为组合内最大单券拖累；场内端恒科与传媒双杀，医药方向ETF小幅收正——与赛道级归因一致。",
  "source": "新浪财经行情", "source_url": "https://finance.sina.com.cn/",
  "sentiment": "负面", "score": 60, "strength": 60, "direction": "利空", "volatility": "中", "brief": "广联达-1.86%为最大单券拖累"},
 {"track": "宏观", "category": "宏观类",
  "title": "卖方对节前节奏的最新判断：中国银河证券认为跨长假风险溢价叠加三季度末机构考核约束，市场或延续震荡与轮动行情；华泰证券指出上周反弹存在「全周成交量继续缩量、后半周市场反转效应变强」两大瑕疵，判断长假前不宜追高；申万宏源等提示节前仅剩1个完整交易日（9/24），9/25 美国8月PCE落于中秋假期内无法提前定价",
  "summary": "卖方对「缩量+反转效应」的定性一致，与组合「零新增买入、维持现有仓位」的纪律完全对齐；节前最后交易日不宜以单日反弹作为加仓依据。",
  "source": "新浪财经/财联社", "source_url": "https://cj.sina.com.cn/articles/view/7651844612/1c815e204001020j1m?finpagefr=p_103",
  "sentiment": "中性", "score": 55, "strength": 55, "direction": "中性", "volatility": "中", "brief": "卖方一致提示节前不宜追高"},
 {"track": "美股标普医药", "category": "宏观类",
  "title": "隔夜美股宏观与医药个股：亚欧股市涨跌互现，美股三大股指期货持稳（道指期货-0.04%、标普期货+0.02%、纳指100期货-0.11%）；S&P Global数据预计显示9月美国商业活动维持在50上方扩张区间，美联储理事Barr稍后发表讲话；隔夜标普500金融板块创3月以来最大单日跌幅（约-2%），Moderna再创新高、Guardant Health获关注，生物科技板块轮动延续",
  "summary": "美股医药端「Moderna新高 + 生科轮动 + Viking催化」的独立强势与金融股受 AI 智能体冲击形成鲜明反差；组合QDII的隔夜映射仍偏正面。",
  "source": "Saxo Bank/Yahoo Finance/Waneye", "source_url": "https://www.home.saxo/content/articles/macro/market-quick-take---oil-slips-under-90-as-bank-shares-slide---23-september-2026-23092026",
  "sentiment": "正面", "score": 60, "strength": 60, "direction": "利多", "volatility": "中", "brief": "美股医药独立强势，生科轮动延续"}
]
'''

data = json.loads(SRC)
ast.parse("x = " + repr(data))  # 语法/结构预检
assert len(data) >= 20, len(data)
for it in data:
    for k in ("track", "category", "title", "summary", "source", "source_url",
              "sentiment", "score", "strength", "direction", "volatility", "brief"):
        assert it.get(k) is not None and it[k] != "", (k, it["title"][:20])
    if not it["source_url"]:
        it["source_url"] = ""

json.dump(data, open(OUT, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print(f"news-close-20260923.json 写入 {len(data)} 条")
print("赛道分布:", dict(Counter(x["track"] for x in data)))
print("类别分布:", dict(Counter(x["category"] for x in data)))
print("方向分布:", dict(Counter(x["direction"] for x in data)))
